### ISSUE TITLE
API request to cloudinary from backend

### ISSUE THREAD

**Issue by lucymk** [InFact-coop/create-refresh#20]
- [ ] send user image to cloudinary 
- [ ] apply stamp (and filter?)
- [ ] send back url of hosted image

**Comment by lucymk** [comment]
@aaronparr this is what we're going to use to host and transform the images: https://cloudinary.com/

It would be great if you could sign up for an account with a temporary password you don't mind sharing with us, then we'll use your account to set everything up.

**Comment by aaronparr** [comment]
try...
user: Aaron.parr@purpose.com
password: eucompliantmemes36
