### ISSUE TITLE
Add Google Analytics support

### ISSUE THREAD

**Issue by martingaston** [InFact-coop/create-refresh#26]
@aaronparr please let us know the details for this

**Comment by developess** [comment]
@lucymk @martingaston 

**Summary of my research on this:**
To track certain events like Aaron has requested, we need to use Google Tag Manager to attach tags to certain elements/events - usually by adding the element ID to the system and specifying the event. I messaged Aaron on #25  to confirm if they will be doing this or we will. 

You also will probably need to add code snippets in the `<head>` to associate the site to your GTM 'container' for it.

I found this tutorial really clear and helpful - https://www.lovesdata.com/blog/google-tag-manager-button-click-tracking. 

I had a little play following the tutorial on my own site and it seemed simple enough.
