### ISSUE TITLE
Connect sign up form to Mailchimp account

### ISSUE THREAD

**Issue by lucymk** [InFact-coop/create-refresh#33]
- use Mailchimp API instead of typeform 
- need details from Create.Refresh

**Comment by lucymk** [comment]
@aaronparr if you can get these details for us that would be great, in case we get around to doing this (probably email them to me though rather than commenting here!).

Also if you go into the ['backlog' milestone](https://github.com/InFact-coop/create-refresh/milestone/3) you can add priority labels to the issues, or drag them in order of importance, so that we know what to work on if we get to that stage.

**Comment by aaronparr** [comment]
Can I find this in this on the MailChimp website? If so, whereabouts?
