### ISSUE TITLE
Burger menu for mobile layout

### ISSUE THREAD

**Issue by lucymk** [InFact-coop/create-refresh#40]
With links to home, privacy, FAQ and social media.

@aaronparr do these social media links point the user directly to the Create.Refresh social media, or do they lead them to share the tool via these platforms?

![screen shot 2018-12-17 at 16 00 52](https://user-images.githubusercontent.com/13594621/50099051-19af5300-0215-11e9-9ca6-1af8e8153c59.png)

**Comment by aaronparr** [comment]
These will be to the social media pages:
FB: www.facebook.com/create.refresh
TW: www.twitter.com/createrefresh
IG: www.instagram.com/create.refresh

The links at the top of the screen will be for sharing the page.

**Comment by lucymk** [comment]
@aaronparr thanks for the links! on mobile I don't think there are any links at the top of the page atm - this is the current sketch file I'm looking at (let me know if this has changed). 
![screen shot 2018-12-18 at 12 52 47](https://user-images.githubusercontent.com/13594621/50155439-f5f71600-02c3-11e9-978c-5c5a2ddc14c1.png)

Also, no worries about this, but please don't close the issues - we need them for our planning as well as asking you questions 😄 thanks!

**Comment by aaronparr** [comment]
Sorry! Didn't mean to close it. I'm still a n00b at Github LOL

Do you think it would work if the Facebook and Twitter icons fell below the drop down box top left? Or would it make more sense to have them further down the view on the mobile site? (If at all). Let me know your steer and I'll get Rav to add them.

**Comment by lucymk** [comment]
There are also icons in the footer which I think link to the social media sites directly. So perhaps the ones in the dropdown work for sharing the tool on social media?

**Comment by aaronparr** [comment]
Okay thanks! Just to clarify, the dropdown button will then autoscroll to sections further down the page? In this case, do we need to add 'share the tool' buttons to the creative?

**Comment by lucymk** [comment]
@aaronparr so I think at the moment the idea is that the buttons in the dropdown (the three lines that then open that full page with the links) will share the tool directly. This is what happens on the desktop site as well. However, I do think this is going to be confusing for users; usually, a facebook or twitter icon links you to the accounts, and if there is a share link then it is made clear that that's what it is, e.g. 
![screen shot 2018-12-19 at 12 13 25](https://user-images.githubusercontent.com/13594621/50219559-88142280-0387-11e9-80ae-854c63954950.png)

Maybe you can ask Rav to make the links to share the tool clearer (on both desktop and mobile). The links to share the cartoon are fine.

**Comment by aaronparr** [comment]
The new Hamburger menu is in the Sketch file: https://drive.google.com/open?id=1IJHHFgzdMn6Wyk4yEpvJJFXLcI-PPAOO ... My bad - wasn't quite sure what you meant but Rav explained to me.

Do you want share copy for these links too?
